# Generated by Django 5.0.2 on 2024-05-28 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='doctor img')),
                ('master_degree', models.ImageField(upload_to='master degree')),
                ('phd_degree', models.ImageField(blank=True, null=True, upload_to='phd degree')),
                ('clink_location', models.CharField(max_length=500)),
                ('medical_center', models.TextField(blank=True, max_length=1000, null=True)),
                ('syndicate_card', models.ImageField(upload_to='syndicate card')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='patient img')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('chronic_diseases', models.TextField(blank=True, max_length=1000, null=True)),
                ('x_ray', models.ImageField(blank=True, null=True, upload_to='x_ray')),
                ('symptoms', models.TextField(blank=True, max_length=1000, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_patient', to='accounts.doctorprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
