# Generated by Django 5.0.2 on 2024-06-04 21:52

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='master_degree',
            field=models.FileField(blank=True, null=True, upload_to='master degree'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='phd_degree',
            field=models.FileField(blank=True, null=True, upload_to='phd degree'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='syndicate_card',
            field=models.FileField(blank=True, null=True, upload_to='syndicate card'),
        ),
    ]
