# Generated by Django 5.0.2 on 2024-06-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_doctorprofile_reset_password_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=400, unique=True),
        ),
    ]
