# Generated by Django 5.0.2 on 2024-03-05 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articls'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company info', 'verbose_name_plural': 'Company info'},
        ),
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 3, 5, 21, 12, 7, 601830, tzinfo=datetime.timezone.utc)),
        ),
    ]
