# Generated by Django 5.0.2 on 2024-07-01 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mri_img1', models.ImageField(blank=True, null=True, upload_to='mri_img', verbose_name='mri image')),
                ('mri_img2', models.ImageField(blank=True, null=True, upload_to='mri_img', verbose_name='mri image')),
                ('mri_img3', models.ImageField(blank=True, null=True, upload_to='mri_img', verbose_name='mri image')),
                ('prediction', models.CharField(blank=True, max_length=900, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prediction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
